language: julia
os:
    - linux
julia:
    - 1.6
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("RandomizedLinAlg")); using Coverage; Coveralls.submit(process_folder());'
    - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("RandomizedLinAlg")); include(joinpath("docs", "make.jl"))'
